package test.system.test;

import java.io.Serializable;

public enum Order implements Serializable{
	// クライアント側に送られる命令
	ON_KYUSYUKYUHAI_REQUESTED(0), ON_TSUMO_HAI_RECEIVED(1), ON_DISCARD_RECEIVED_0(
			1), ON_TSUMOGIRI_RECEIVED(1), ON_CHIABLE_INDEX_LISTS_RECEIVED(1), ON_PONABLE_INDEX_LISTS_RECEIVED(
			1), ON_ANKANABLE_INDEX_LISTS_RECEIVED(1), ON_MINKANABLE_INDEX_LISTS_RECEIVED(
			1), ON_KAKANABLE_INDEX_LISTS_RECEIVED(1), ON_REACHABLE_INDEX_LIST_RECEIVED(
			1), ON_RON_REQUESTED(0), ON_TSUMO_AGARI_REQUESTED(0), ON_FIELD_RECEIVED(
			9), ON_DISCARD_RECEIVED_1(3), ON_NAKI_RECEIVED(2), ON_REACH_RECEIVED(
			2), ON_GAME_START_RECEIVED(3), ON_START_KYOKU_RECEIVED(4), ON_KYOKU_RESULT_RECEIVED(
			5), ON_GAME_RESULT_RECEIVED(1), ON_GAME_OVER_RECEIVED(0),
	// サーバ側に送られる命令
	ON_DISCARD_INDEX_RECEIVED(1), ON_CHI_INDEX_LIST_RECEIVED(1), ON_PON_INDEX_LIST_RECEIVED(
			1), ON_ANKAN_INDEX_LIST_RECEIVED(1), ON_MINKANABLE_INDEX_RECEIVED(1), ON_KAKANABLE_INDEX_RECEIVED(
			1), ON_REACH_INDEX_RECEIVED(1), ON_KYUSYUKYUHAI_RECEIVED(1), ON_TSUMO_ARGARI_RECEIVED(
			0), ON_GAME_REQUESTED(1), ON_NEXT_KYOKU_REQUESTED(0),
	// サーバ,クライアント共に送られる命令
	ON_RON_RECEIVED(1);
	/**
	 * 命令の引数の数
	 */
	private int count;

	private Order(int count) {
		this.count = count;
	}

	public int getCount() {
		return count;
	}
}
